import type { Metadata } from "next";
import "./globals.css";
import { ExpenseContextProvider } from "./context/ExpenseContextProvider";

export const metadata: Metadata = {
  title: "Personal Finance Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ExpenseContextProvider>{children}</ExpenseContextProvider>
      </body>
    </html>
  );
}
